version: "3.8"
services: 
  api:
    build: ./src
    ports: 
      - 5000:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Docker
    env_file: docker.env
    depends_on: 
      - vault

  vault:
    image: vault:1.5.5
    ports:
      - "8200-8201:8200-8201"
